services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - db_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/alfa_mail.db

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mapujemy plik z folderu nginx do konfiguracji
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mapujemy certyfikaty (muszą być w głównym folderze AlfaMail)
      - ./nginx.crt:/etc/nginx/conf.d/nginx.crt:ro
      - ./nginx.key:/etc/nginx/conf.d/nginx.key:ro
      # Mapujemy frontend (tam gdzie masz register.html, index.html, app.js)
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  db_data: